server:
  port: 12345

spring:
  rabbitmq:
    host: localhost
    username: localrabbit
    password: localrabbit
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        prefetch: 10

logging:
  level:
    org: ERROR
