server:
  port: 12345

spring:
  rabbitmq:
    host: localhost
    username: localrabbit
    password: localrabbit
    virtual-host: /
#    listener:
#      simple:
#        acknowledge-mode: auto
#        retry:
#          enabled: true
#          initial-interval: 3s
#          max-interval: 10s
#          max-attempts: 5
#          multiplier: 2


logging:
  level:
    org: ERROR
