server:
  port: 12345

spring:
  rabbitmq:
    host: localhost
    username: localrabbit
    password: localrabbit
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

logging:
  level:
    org: ERROR
